---
- name: Start Vector container
  docker_container:
    name: vector
    image: "netflixoss/vector:latest"
    state: started
    restart_policy: unless-stopped
    recreate: yes
    ports:
      - "8081:80"
